export const CLEAR_MANIFEST_FETCH_RESPONSE = 'CLEAR_MANIFEST_FETCH_RESPONSE';
export const SET_MANIFEST_FETCH_RESPONSE = 'SET_MANIFEST_FETCH_RESPONSE';
export const UPDATE_SEARCH_TEXT = 'UPDATE_SEARCH_TEXT';
export const UPDATE_MANIFEST_STATUS = 'UPDATE_MANIFEST_STATUS';
