export const MANIFEST_STATUS_LOADING = 'MANIFEST_STATUS_LOADING';
export const MANIFEST_STATUS_LISTED = 'MANIFEST_STATUS_LISTED';
export const MANIFEST_STATUS_DOWNLOADING = 'MANIFEST_STATUS_DOWNLOADING';
export const MANIFEST_STATUS_COMPLETE = 'MANIFEST_STATUS_COMPLETE';
